FROM python:3.9-alpine

# Install build dependencies
RUN apk add --no-cache \
    gcc \
    musl-dev \
    linux-headers \
    binutils

WORKDIR /app

# Copy files
COPY file_watcher.py ./

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install pyinstaller watchdog requests toml

# Build with PyInstaller with static linking
RUN pyinstaller --onefile --name kh-file-watcher-static --strip file_watcher.py

# Make executable
RUN chmod +x dist/kh-file-watcher-static
